### ISSUE TITLE
可是他code裡面的T原本是設為1的樣子，你有看懂他T的設置嗎，那時候寫看他T的維度感覺沒用到

### ISSUE THREAD

**Issue by 108360215** [HeuristicLU/EMS-yolo#1]

**Comment by HeuristicLU** [comment]
我才刚把训练 推理 评估跑通，我慢慢研究下看看再交流

**Comment by ColsonZhang** [comment]
在yolo.py和common.py里面都设置了time_window这个参数。可以同时修改这个参数为更高的时间步。论文里面Figure4好像也展示了一个模型不同时间步的结果。

**Comment by zhangfzR** [comment]
> 在yolo.py和common.py里面都设置了time_window这个参数。可以同时修改这个参数为更高的时间步。论文里面Figure4好像也展示了一个模型不同时间步的结果。

你好，请问你有弄懂这个问题吗？

**Comment by sumingming123** [comment]
Have you encountered this problem? I have agreed to the time_window setting parameters. This error is still displayed.Starting training for 250 epochs...

 Epoch   gpu_mem       box       obj       cls    labels  img_size
0%| | 0/1 [00:00<?, ?it/s] /content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py:343: FutureWarning: torch.cuda.amp.autocast(args...) is deprecated. Please use torch.amp.autocast('cuda', args...) instead.
with amp.autocast(enabled=cuda):
0%| | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 662, in
main(opt)
File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 559, in main
train(opt.hyp, opt, device, callbacks)
File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 344, in train
pred = model(imgs) # forward
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
return forward_call(*args, **kwargs)
File "/content/drive/MyDrive/EMS_YOLO_LU/models/yolo.py", line 140, in forward
input[i] = x
RuntimeError: expand(torch.FloatTensor{[47, 5, 3, 320, 320]}, size=[47, 5, 3, 320]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)

**Comment by Qiaoyi-Su** [comment]
> 在yolo.py和common.py里面都设置了time_window这个参数。可以同时修改这个参数为更高的时间步。论文里面Figure4好像也展示了一个模型不同时间步的结果。

是的

**Comment by Qiaoyi-Su** [comment]
T时间步有被用到，在原本代码中设置的是4
