### ISSUE TITLE
请问您有跑通calculate.py吗？就是计算fire rate的，谢谢！

### ISSUE THREAD

**Issue by mengqiShen** [HeuristicLU/EMS-yolo#3]

**Comment by JunZhou123** [comment]
我也想知道

**Comment by sumingming123** [comment]
Have you encountered this problem? I have agreed to the time_window setting parameters. This error is still displayed.Starting training for 250 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/1 [00:00<?, ?it/s]                                                               /content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py:343: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=cuda):
  0%|          | 0/1 [00:00<?, ?it/s]                                                               
Traceback (most recent call last):
  File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 662, in <module>
    main(opt)
  File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 559, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 344, in train
    pred = model(imgs)  # forward
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/EMS_YOLO_LU/models/yolo.py", line 140, in forward
    input[i] = x
RuntimeError: expand(torch.FloatTensor{[47, 5, 3, 320, 320]}, size=[47, 5, 3, 320]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)

**Comment by NeuFarm** [comment]
你们这个计算发放率的跑通了吗？

**Comment by JunLi0514** [comment]
我运行的是detect.py 处理静态图像，args修改weights, source，在common.py mem_update forward()上面加了@get_local('output')，注释掉detect.py里面ChannelAttention及下面的几个attention，只保留mem_update.forward相关，是可以跑通了

**Comment by mengqiShen** [comment]
> 我运行的是detect.py 处理静态图像，args修改weights, source，在common.py mem_update forward()上面加了@get_local('output')，注释掉detect.py里面ChannelAttention及下面的几个attention，只保留mem_update.forward相关，是可以跑通了

谢谢，我也跑通了
